runtime bundle/pathogen/autoload/pathogen.vim
execute pathogen#infect()

set nocompatible

syntax on
filetype on
filetype plugin on
filetype indent on

set expandtab
set shiftwidth=4
set tabstop=4
set smarttab

set ai
set nosmartindent
set nowrap

set encoding=utf-8 fileencoding=utf-8
set nobackup nowritebackup noswapfile autoread
set number hlsearch incsearch ignorecase smartcase

set ignorecase incsearch smartcase showmatch showcmd hidden

set mouse=a

set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,.pyc

let g:ctrlp_custom_ignore='\.pyc'
let g:ctrlp_working_path_mode=0
let g:ctrlp_mruf_last_entered=1

let mapleader=","
nnoremap <leader>p :CtrlP<CR>
nnoremap <leader>b :CtrlPBuffer<CR>

set background=dark
let g:solarized_termtrans=1
let g:solarized_termcolors=256
let g:solarized_contrast="high"
let g:solarized_visibility="high"
colorscheme solarized

set clipboard=unnamed

let g:ackhighlight=1

set foldmethod=indent
set foldlevel=99
set foldenable

:au FocusLost * :set number
:au FocusGained * :set relativenumber
autocmd InsertEnter * :set number
autocmd InsertLeave * :set relativenumber

:set cursorline
hi CursorLine ctermbg=235

set laststatus=2

hi User1 ctermfg=234 ctermbg=33
hi User2 ctermfg=254 ctermbg=235
hi User3 ctermfg=125 ctermbg=235
hi User4 ctermfg=125 ctermbg=234
hi User5 ctermfg=240 ctermbg=235
hi User6 ctermfg=234 ctermbg=240

set statusline=
set statusline+=%1*[%n]
set statusline+=%2*\ %<%F
set statusline+=%3*\ %{fugitive#statusline()}
set statusline+=%4*\ %m
set statusline+=%=
set statusline+=%5*[%c]
set statusline+=%6*[%l/%L]
