#!/bin/bash

sudo -v

brew update
brew upgrade

brew tap homebrew/versions
brew tap phinze/homebrew-cask

if [ ! -d "~/Library/LaunchAgents" ]; then
    mkdir ~/Library/LaunchAgents
fi

brew install ack
brew install brew-cask
brew install git
brew install irssi
brew install imagesnap
brew install libjpeg

brew install memcached
ln -sfv /usr/local/opt/memcached/*.plist ~/Library/LaunchAgents
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.memcached.plist

brew install mongodb
ln -sfv /usr/local/opt/mongodb/*.plist ~/Library/LaunchAgents
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mongodb.plist

brew install node
brew install pass
brew install pianobar
brew install pyenv

brew install redis
ln -sfv /usr/local/opt/redis/*.plist ~/Library/LaunchAgents
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist

brew install solr
brew install tmux
brew install tig
brew install wget
brew install zsh

brew cask install dropbox
brew cask install tunnelblick
brew cask install dropbox
brew cask install google-chrome
brew cask install growlnotify
brew cask install heroku-toolbelt
brew cask install slack
brew cask install audacity

# http://eafarris.com/xplanet-on-osx.html
brew cask install xquartz
brew install xplanet

brew cleanup
